### ISSUE TITLE
Inkscape plugin

### ISSUE THREAD

**Issue by Xaviju** [reneepadgham/diverseui#1]
I have created a plugin for Inkscape using your API ;)
Right now its part of a list of placeholder services but I can convert it into a single plugin if you prefer

https://github.com/Xaviju/inkscape-placeholder/tree/master/diverseui

![image](https://user-images.githubusercontent.com/1343702/31704532-15c6a0b8-b3e2-11e7-8e16-09f130b6f553.png)

**Comment by yefim** [comment]
Awesome work!
